@startuml
!pragma layout smetana

node "client node" {
    [fat client]
}


package "server side" {
    [orchestration]
    package "services" {
        [Transformer]
        [SMS Gateway]
        [SMTP Gateway]
    }
    database {
        [TDB]
    }
}

[fat client] -r-> [orchestration]
[orchestration] -> [TDB]
[orchestration] -d-> [Transformer]
[orchestration] -> [SMS Gateway]
[orchestration] -> [SMTP Gateway]


@enduml
