@startuml
!pragma layout smetana
!pragma horizontalLineBetweenDifferentPackageAllowed

node "client node" {
    [fat client]
}

component "server side" {
    () "in" as in
    [Transformer]
    [SMS Gateway]
    [SMTP Gateway]
    database {
        [TDB]
    }
}

[fat client] -r-> in : uses
in -d-> [TDB] : uses
in -r-> [Transformer] : queue
[Transformer] -d-> [SMS Gateway] : queue
[Transformer] -d-> [SMTP Gateway] : queue

@enduml
