@startuml
!pragma layout smetana
!pragma horizontalLineBetweenDifferentPackageAllowed

node "client node" {
    [fat client]
}

component "server side" {
    [orchestration]
    package "services" {
        [Transformer]
        [SMS Gateway]
        [SMTP Gateway]
    }
    database {
        [TDB]
    }
}

[fat client] -r-> [orchestration] : uses
[orchestration] -> [TDB]
[orchestration] -d-> [Transformer]
[orchestration] -> [SMS Gateway]
[orchestration] -> [SMTP Gateway]

@enduml
