@startuml
!pragma layout smetana
!pragma horizontalLineBetweenDifferentPackageAllowed

node "client node" {
    [fat client]
}

cloud "AWS" {
    () "API Gateway" as in
    [ <<Lambda>>\nTransformer ] as trans
    [SNS]
    database "S3" {
        [object store]
    }
}

[fat client] -r-> in : uses
trans -d-> [object store] : uses
in -r-> trans : sqs
trans -r-> [SNS] : sqs

@enduml
